version: "3.9"

services:
  linux-basics:
    build: .
    container_name: linux-basics
    restart: unless-stopped
    ports:
      - "5021:5021"

    read_only: false

    tmpfs:
      - /tmp

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL